### ISSUE TITLE
`xs: 0px` cannot be assigned as minimum breakpoint

### ISSUE THREAD

**Issue by fvandenbulck** [mg901/styled-breakpoints#1120]
Hi guys !

In a NextJs project, I use your library for handling easily breakpoints (thanks by the way).

Unfortunately, this code below seems does not work since this following error has triggered :
`Error: [styled-breakpoints]: 'xs: 0px' cannot be assigned as minimum breakpoint.`

FYI, I use default breakpoint values.

```typescript
export const Container = styled.div<WrapperProps>`
  ${space}

  margin-left: auto;
  margin-right: auto;

  ${between('xs', 'md')} {
    width: 90%;
  }

  ${up('md')} {
    width: 70%;
  }
`;
```

I remember a few months ago, this kind of code worked.

I use **next 12.0.7** (which uses SWC instead of Babel now), **styled-components 5.3.3** and **styled-breakpoints 10.2.1**.

Thanks for your help :-).

**Comment by mg901** [comment]
Hi, @fvandenbulck !) Just replace your code with this

export const Container = styled.div<WrapperProps>`
  ${space}

  margin-left: auto;
  margin-right: auto;
  width: 90%;

  ${up('md')} {
    width: 70%;
  }
`;

**Comment by mg901** [comment]
@fvandenbulck If you have any questions, ask. I will gladly help you.

**Comment by mg901** [comment]
@fvandenbulck if you have any questions, ask. I will gladly help you.

**Comment by fvandenbulck** [comment]
Thanks @mg901, it works like that.

What was the issue exactly here ? `xs`can not be used in `between` function ?

**Comment by mg901** [comment]
@fvandenbulck when you create a layout from 0px, no breakpoints are needed. There is a need for them after (from `sm` onwards)

**Comment by fvandenbulck** [comment]
@mg901 You're right. So, it's why `sm` is explicitly forbidden in this case.  Thanks for your answer ;-).
