### ISSUE TITLE
Override default breakpoints globally

### ISSUE THREAD

**Issue by rolandtoth** [mg901/styled-breakpoints#1260]
Many thanks for this package, I just started to use it in a project and it's very similar to what I have used for SCSS in the past.

One thing I didn't find is that is there a way to override the default breakpoints, globally? In the readme as I see overriding can be done with `createTheme` and `ThemeProvider`.

Fortunately the project uses the same breakpoints as the defaults so it's not a big issue right now, but later a global customization may be needed.

**Comment by mg901** [comment]
@rolandtoth hi! Thank you for your interest in styled-breakpoints :) Please describe there you may need global breakpoints? Do it in the sandbox like [codesandbox](https://codesandbox.io/?from-app=1) or etc... Maybe I can help you?

**Comment by rolandtoth** [comment]
Hi @mg901 , I mean that the package comes with a default breakpoint set, but what if someone needs different values, eg. 777 instead of 768? If there would be a way to set the values somewhere that the package would use instead of the built-in values everywhere, that would be great.

I'm using the package in a Next.js project, tried a few things and this way it works but I don't think it's optimal:

![image](https://user-images.githubusercontent.com/5349356/179984409-8c65324d-4ebe-4a39-b38b-be884c01cadc.png)

```
const MyTheme: DefaultTheme = {
  // breakpoints: createTheme({
  //   xs: '0px',
  //   sm: '576px',
  //   md: '777px',
  //   lg: '999px',
  //   xl: '1200px',
  //   xxl: '1400px',
  // })["styled-breakpoints"].breakpoints,
  
  ["styled-breakpoints"]: {
    breakpoints: {
      xs: '0px',
      sm: '576px',
      md: '777px',
      lg: '999px',
      xl: '1200px',
      xxl: '1400px',
    }
  },
...
```

+ setting ThemeProvider on the very top PageWrapper element:

```
      <ThemeProvider theme={MyTheme}>
        <PageWrapper>
           ...
```

I can live with this too but please suggest if there's a better way.

Easier would be to just set the default breakpoints of the package once (globally).

**Comment by mg901** [comment]
@rolandtoth maybe [so](https://codesandbox.io/s/mobile-first-forked-w8z9o8?file=/src/app.tsx:232-258)?

**Comment by rolandtoth** [comment]
Yes, it's working fine, thanks!

Also I'm using this for Storybook if anyone needs it (preview.js):

```
export const decorators = [
  (Story) => (
    <ThemeProvider theme={MyTheme}>
      {/* <GlobalCSS /> */}
      <Story />
    </ThemeProvider>
  ),
];
```
