### ISSUE TITLE
`xs: 0px` cannot be assigned as minimum breakpoint.

### ISSUE THREAD

**Issue by nedelyux** [mg901/styled-breakpoints#1346]
Then why is it in default Breakpoints if I can't write a regular piece of code

`[up('xs')(props)]: {
  flexBasis: "calc(100% / 1)",
},`

`[up('sm')(props)]: {
  flexBasis: "calc(100% / 2)",
},`

`[up('md')(props)]: {
  flexBasis: "calc(100% / 3)",
},`

I don't want to write down('sm')

**Comment by mg901** [comment]
@nedelyux I don't understand what do you want?

**Comment by nedelyux** [comment]
@mg901 Sure. I have an error when use up('xs'). I want to get valid code when I think about styles from 0px to SM breakpoint, instead of down('sm')

https://codesandbox.io/s/crazy-oskar-levk0i?file=/src/App.js
https://levk0i.csb.app/

**Comment by mg901** [comment]
@nedelyux Hi, do [so](https://codesandbox.io/s/dreamy-currying-1vvwvc?file=/src/App.js)
Next time see an example [here](https://codesandbox.io/s/rough-wave-u0uuu?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fapp.tsx&theme=dark)

Thank you for your question.)

**Comment by mg901** [comment]
@nedelyux you are right. Indeed, the behavior of the `up` function is not as expected.
