### ISSUE TITLE
Customizing breakpoints throws undefined error

### ISSUE THREAD

**Issue by iandjx** [mg901/styled-breakpoints#1511]
I customized the breakpoint as follows

```
const theme = {
  ...primaryTheme,
  ...createStyledBreakpointsTheme({
    breakpoints:{
      sm:'400px',
      md:'700px',
      lg:'1024px'

    }
  })
};
```
which throws this error

`Cannot read properties of undefined (reading 'sm')`

I've forked the example to replicate the issue. Please see link below.
https://codesandbox.io/s/mobile-first-forked-b9esm9?file=/src/app.tsx

**Comment by mg901** [comment]
@iandjx  Thank you, bro.
