### ISSUE TITLE
Cannot find module 'styled-breakpoints/use-media-query'

### ISSUE THREAD

**Issue by smurf-ss** [mg901/styled-breakpoints#1571]
<img width="694" alt="image" src="https://github.com/mg901/styled-breakpoints/assets/59644046/efd27a5f-6560-46ef-b33c-f806c78f12be">
<img width="661" alt="image" src="https://github.com/mg901/styled-breakpoints/assets/59644046/b48841e7-9858-4940-9cda-dfc14aed0770">

**Comment by smurf-ss** [comment]
@mg901 I used 
 "next": "12.1.0",
  "react": "17.0.2",
  "react-dom": "17.0.2",
  "styled-breakpoints": "11.1.1",

**Comment by smurf-ss** [comment]
> 



> @smurf-ss, hi.) Please, specify what version of styled-breakpoints do you use?

I used
"next": "12.1.0",
"react": "17.0.2",
"react-dom": "17.0.2",
"styled-breakpoints": "11.1.1",

**Comment by mg901** [comment]
@smurf-ss Latest version is 12.1.5
