### ISSUE TITLE
Feature Request: Support min-Height max-Height

### ISSUE THREAD

**Issue by AdlerJS** [mg901/styled-breakpoints#1847]
Hey @mg901,

First want to say thanks for the library its been awesome for our needs. I'm running into a situation where I have a table on our application and based on the height want to set the number of rows rendered to a given number. I was hoping to use this library as we have been using it for width calculations in our application already. Is there a plan / interest to support `min-height` & `max-height` via the same API. If we can get an API agreement up I would be willing to do the work and open a PR. Just let me know. Thanks!

**Comment by mg901** [comment]
@AdlerJS, I need to find some time to solve this problem, and I can't do it quickly, because the configuration contains breakpoints only for the with. Explain please, about your API's vision.
