### ISSUE TITLE
Can't use breakpoints as specified in the documentation

### ISSUE THREAD

**Issue by f4xxf4xx** [mg901/styled-breakpoints#239]
Using version 6.6.3, I'm trying to use styled-breakpoints as specified in the docs: 

```
export const StyledDrawer = styled(Drawer)`
  && {
    ${down('tablet')} {
      color: lightcoral;
    }
  }
`;
```
And I'm getting this error : 

> Uncaught Error: [styled-breakpoints]: 'mobile' is invalid breakpoint name. Use 'keys, values, up, down, between, only'

I tried with different breakpoints (mobile, desktop), and I am still getting this error.

**Comment by mg901** [comment]
@f4xxf4xx Good time. Why did you close the issue? Have you solved the problem? If so, what did you do wrong?

**Comment by ifndefdeadmau5** [comment]
@mg901 I'm getting this too, it's bit surprised that basic usage didn't work for me.
styled-components version is 4.3.2
