### ISSUE TITLE
can't work with rebass or styled-system

### ISSUE THREAD

**Issue by jiangbo2015** [mg901/styled-breakpoints#256]
the type of styled-breakpoints is  object
```
breakpoints={
sm: 0,
md: 992,
lg: 1024
}
```
the type of rebass or styled-system is array
```
breakpoints=['40em', '60em', '80em']
```

https://github.com/styled-system/styled-system/blob/master/docs/responsive-styles.md#using-objects

###### can we make it work with array? breakpoints will be array or object

**Comment by mg901** [comment]
@jiangbo2015, you need to choose one thing. Styled System describes the css in the markup. Styled-breakpoints on the contrary, seeks to remove styles from the markup.

**Comment by mg901** [comment]
In any case, styled-breakpoints is not a universal solution for all projects and cannot cover all possible cases.

**Comment by jiangbo2015** [comment]
ok thanks
