### ISSUE TITLE
Add option to add orientation media-query: portrait or landscape

### ISSUE THREAD

**Issue by martinbroos** [mg901/styled-breakpoints#270]
Would be nice since with iPad pro the resolutions of portrait mode is already 1024px wide.
This would give us a bit more control, especially when combining with min and max-width.

Thanks for all your work.

**Comment by mg901** [comment]
@martinbroos,  What api functions would you like to see?

**Comment by mg901** [comment]
@martinbroos done! Enjoy using.)

**Comment by martinbroos** [comment]
Awesome looks good, thanks for the fast implementation.
