### ISSUE TITLE
Can not use below function on highest breakpoint

### ISSUE THREAD

**Issue by Ontopic** [mg901/styled-breakpoints#4]
This should be possible, right?

**Comment by mg901** [comment]
@Ontopic Hello! Sorry for the long answer )) You cannot use the function below for the highest breakpoint, since it takes the last maximum breakpoint value. The highest breakpoint simply does not have it.

**Comment by Ontopic** [comment]
Thanks for your detailed response (and a lovely package).

Maybe a more detailed error message (perhaps even linking to this issue) would be nice.

**Comment by Ontopic** [comment]
We'll be submitting a pull request, it seems there is a small mixup.

**Comment by mg901** [comment]
@Ontopic, Deal!

**Comment by mg901** [comment]
@Ontopic At your request, it made the message more obvious.

**Comment by sschottler** [comment]
This affects the `between` method too. I found it a bit unintuitive that the 2nd parameter was inclusive. The api seems to differ from other similar packages with a `between` concept:

https://github.com/morajabi/styled-media-query#between

https://github.com/jameslnewell/styled-components-breakpoint#breakpointgte-lt
