### ISSUE TITLE
Doesn't handle breakpoints already specified in em.

### ISSUE THREAD

**Issue by mikestopcontinues** [mg901/styled-breakpoints#432]
Hey, I see there's a toEm method that's assuming any value passed in is going to be pixels. There should be a check to see if the values are already ems.

**Comment by mg901** [comment]
@mikestopcontinues, thanks for the feedback. Great point. I will add validation, which would warn that all transmitted values should be in pixels.

**Comment by mg901** [comment]
@mikestopcontinues, [done](https://github.com/mg901/styled-breakpoints/releases)

**Comment by mikestopcontinues** [comment]
Cheers!
