### ISSUE TITLE
Orientation Landscape

### ISSUE THREAD

**Issue by sptGabriel** [mg901/styled-breakpoints#499]
Hello I would like to know if you have orientation landscape?

**Comment by mg901** [comment]
@sptGabriel,  hi! Yes of  course are there. You can specify one of the values
```up("md", "landscape")``` or ```up("md", "portrait")```

**Comment by sptGabriel** [comment]
yeah really, is it possible to create a custom media without having to go through theme?

**Comment by mg901** [comment]
@sptGabriel nope
