### ISSUE TITLE
Proposal: Add example of usage with object notation

### ISSUE THREAD

**Issue by rafauke** [mg901/styled-breakpoints#529]
Hey hello,

Thanks for the library, it is really useful :+1: I would like to propose to document usage of `styled-breakpoints` when using object notation in order to explain that breakpoint functions (`up`, `down` etc.) are curried and that `props` have to be passed explicitly:

```js
const MyComponent = styled('div')(props => ({
  color: props.theme.colors.primary,
  fontSize: '1.5rem',
  [up('sm')(props)]: {
    fontSize: '1rem'
  }
}))
```

By `props` I mean an object with a compatible "interface" i.e. containing a `theme` property.

I can create a PR for that if that's ok.

Cheers!

**Comment by mg901** [comment]
@rafauke, Hi!) Glad my work has benefited you. Yes, this is a great proposition. Under each existing example, you can place a description for object notation.

**Comment by mg901** [comment]
@rafauke done!) Thank you!
