### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by alexolefirenko** [mg901/styled-breakpoints#53]
I tried to find typings for the library and unfortunately have not found anything... Do you have plans to develop them?

**Comment by mg901** [comment]
@alexolefirenko, thank you for your interest in my tool.  I couldn't imagine that the tool would be so much in demand, especially by TypeScript developers. In the next 2 / 3 days I will add types for ts. Do I need to do this only for functions up, down, only, between ? or do I need types for something else?

**Comment by alexolefirenko** [comment]
@mg901 yeah, this tool is small and in the same time powerful and make code more readable 👍
So, it would be good if you added ts support as good as flow supports. I expected to see for each of exported method typings and I think that it's good. Ping me if you need some help, I was thinking to make them today, but have not to find time to do this (

**Comment by mg901** [comment]
@alexolefirenko I added types for TypeScript. You're need to download the latest version. Please Let me know if anything's wrong. I'm expecting a Pull Request from you.

**Comment by alexolefirenko** [comment]
@mg901 
Thank you, I have made some changes that fit our requirements :). Check it, please.

**Comment by mg901** [comment]
@alexolefirenko Done! Thank you so much!
