### ISSUE TITLE
Hook API: useBreakpoint

### ISSUE THREAD

**Issue by samholmes** [mg901/styled-breakpoints#682]
I propose a hooks API:

```ts
import { up, useBreakpoint } from 'styled-breakpoints`

const isMobile = useBreakpoint(up('tablet'));
```

Working Implementation:

```ts
import { useState, useEffect } from 'react';
import { useTheme } from 'styled-components';

export const useBreakpoint = (breakpoint: (z: { theme: any }) => string) => {
  const theme = useTheme();
  const query = breakpoint({ theme }).replace(/^@media/, '');

  const mq = window.matchMedia(query);
  const [isBreak, setIsBreak] = useState(mq.matches);

  useEffect(() => {
    function handleResize() {
      setIsBreak(window.matchMedia(query).matches);
    }

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return isBreak;
};

export default useBreakpoint;
```

**Comment by mg901** [comment]
@samholmes, thank you for your interest in styled-breakpoints.) When creating styled-breakpoints, I set myself the goal of declaratively describing component styles and removing any mention of css from markup. Add and remove styles without affecting jsx.

What problem did you encounter that caused you to use hooks? What problem does the proposed approach solve?

**Comment by samholmes** [comment]
I created the hook to use the same breakpoints defined in my theme in my component's logic, specifically to enable and disable certain animations using react-spring that are only relevant on mobile layouts. There's a lot of one could do with this hook and I imagine a lot of problems can be solved with this hook.

**Comment by mg901** [comment]
@samholmes, could you show examples (code) of problems and their solutions using a hook?

**Comment by rmariuzzo** [comment]
Maybe something like:

```ts
const desktop = useBreakpoint(_ => _.theme.media.desktop)

return desktop ? <Table /> : <List />
```

The benefit would be to be able to not render both and keep one hidden. This would require some sort of window resize handler to trigger updates.

**Comment by ptcampbell** [comment]
Yeah this would be great. I'm using this hook to rearrange elements in the DOM at certain breakpoints. And in some cases, strings may be different for different screen widths.

**Comment by mg901** [comment]
@samholmes, thank you so much for the idea. As time shows, users really need it.

**Comment by mg901** [comment]
@rmariuzzo @samholmes @ptcampbell @sdowding supported since [v8.2.0](https://github.com/mg901/styled-breakpoints/releases/tag/v8.2.0)
