### ISSUE TITLE
Additional range selectors

### ISSUE THREAD

**Issue by iRyanBell** [mg901/styled-breakpoints#848]
Conceptually, I like to think of a breakpoint as a threshold value. If the breakpoint value is `500px` I would expect an `above` query to be >500px and a `below` query to be <500px.

In the example:

```
{
  sm: '576px',
  md: '768px',
  lg: '992px',
  xl: '1200px',
}

up('md') => '@media (min-width: 768px) { ... }'
only('md') => '@media (min-width: 768px) and (max-width: 991.98px) { ... }'
down('md') => '@media (max-width: 991.98px) { ... }'
between('md', 'lg') => '@media (min-width: 768px) and (max-width: 1199.98px) { ... }'
```

`up('md')` makes complete sense as being greater than or equal to md.

`only('md')` also makes total sense as selecting `[md, lg)`.

`down('md')` I don't agree with, as it _seems_ like it should be <_md_. Instead, it is <_lg_.

`between('md', 'lg')` follows this same logic as `down`, querying from `[md, xl)`, when I would prefer`[md, lg)`

As this is currently written, there is no way to select `down()` from the lowest breakpoint, which is often the most useful breakpoint, as things are most likely to break the layout at this extreme value. `down('xs')` is currently interpreted as **<Sm** (not <Xs).

---

### Proposed solution:

The names for this new query could be `downFrom` or `upTo`.

```
downFrom('md') => '@media (max-width: 767.8px) { ... }'
upTo('md') => '@media (max-width: 767.8px) { ... }'
```

Alternatively, `down('md', orientation, true)` could use a third argument to specify the max-width of `md` rather than the next higher breakpoint (lg). Renaming `calcMinWidth` -> `getWidthAtBreakpoint` and `calcMaxWidth` -> `getWidthAtNextBreakpoint` also helps to clarify the functionality.

Here's a feature proposal of how the latter could look with 3 additional unit tests: https://github.com/iRyanBell/styled-breakpoints/tree/feat/is-below-break-proposal

**Comment by mg901** [comment]
@iRyanBell, good time.  Thanks for using style-breakpoints.  All of the above problems only arise because you ignore the mobile first approach. The existing api is enough to cover all your needs.

**Comment by iRyanBell** [comment]
Can you elaborate more on the mobile first approach?

It's not quick clear to me why `up('md')` is relative to md (up from md). And down('md') targets a different breakpoint than md (down from sm).

**Comment by mg901** [comment]
@iRyanBell if you have any difficulties with solving existing problems, please send a link with an example code to codesandbox / stackblitz.  I will gladly help you.

**Comment by iRyanBell** [comment]
> @iRyanBell if you have any difficulties with solving existing problems, please send a link with an example code to codesandbox / stackblitz. I will gladly help you.

How would you ideally query down from `sm` (ie. a width no greater than a max value of 576px), given the breakpoints definition of:

```
{
  sm: '576px',
  md: '768px',
  lg: '992px',
  xl: '1200px',
}
```

**Comment by mg901** [comment]
@iRyanBell take a look at this [example](https://codesandbox.io/s/rough-wave-u0uuu?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fapp.tsx&theme=dark)

**Comment by mg901** [comment]
> Can you elaborate more on the mobile first approach?
> 
> It's not quite clear to me why `up('md')` is relative to md (up from md). And `down('md')` performs _down from lg_.

Mobile first - from smallest to largest.
Desktop first - from largest to smallest.

**Comment by iRyanBell** [comment]
> @iRyanBell take a look at this [example](https://codesandbox.io/s/rough-wave-u0uuu?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fapp.tsx&theme=dark).

Ah, I see what you mean now by the mobile first approach! That works, just using `up` which references the supplied breakpoint rather than trying to use `down` which picks a different breakpoint.

So, from this perspective, you can't write a media query < sm (or your lowest breakpoint) as a sort of "it's a feature, not a bug" mentality.

**Comment by mg901** [comment]
@iRyanBell "Desktop first" has many drawbacks. If following the "mobile first" principle you add the functionality you need, then in "desktop first" you need to hide what you already have and you constantly have to write display: none;

**Comment by iRyanBell** [comment]
> @iRyanBell "Desktop first" has many drawbacks. If following the "mobile first" principle you add the functionality you need, then in "desktop first" you need to hide what you already have and you constantly have to write display: none;

Fwiw, with the proposed changes (or some way to say `max-width: first_break`), the library could be truly mobile-first / desktop-first agnostic. The examples do include a desktop-first block https://www.npmjs.com/package/styled-breakpoints#desktop-first

**Comment by mg901** [comment]
@iRyanBell maybe these videos will help you think mobile first. 
[video](https://www.google.com/search?newwindow=1&sxsrf=ALeKk01ujWg6x_98U3ZyUnctmuYJ6zrt3A:1606037538062&q=luke+wroblewski+mobile+first&tbm=vid&source=univ&tbo=u&sa=X&ved=2ahUKEwihwM6H7JXtAhVHiIsKHSjwAMgQt8YBKAF6BAgGEDA&biw=1680&bih=945)
[book](https://www.amazon.com/Mobile-First-Luke-Wroblewski/dp/1937557022#customerReviews)

**Comment by iRyanBell** [comment]
> @iRyanBell maybe these videos will help you think mobile first.
> [video](https://www.google.com/search?newwindow=1&sxsrf=ALeKk01ujWg6x_98U3ZyUnctmuYJ6zrt3A:1606037538062&q=luke+wroblewski+mobile+first&tbm=vid&source=univ&tbo=u&sa=X&ved=2ahUKEwihwM6H7JXtAhVHiIsKHSjwAMgQt8YBKAF6BAgGEDA&biw=1680&bih=945)
> [book](https://www.amazon.com/Mobile-First-Luke-Wroblewski/dp/1937557022#customerReviews)
> 
> Bootstrap
> <img alt="Снимок экрана 2020-11-22 в 12 36 33" width="721" src="https://user-images.githubusercontent.com/7874664/99900265-95e32880-2cbf-11eb-8320-a9a614d13662.png">
> 
> Zurb Foundation
> <img alt="Снимок экрана 2020-11-22 в 12 37 27" width="312" src="https://user-images.githubusercontent.com/7874664/99900274-a2678100-2cbf-11eb-9c71-087aa8455974.png">

I'm totally on board with a mobile-first mindset for cascading styles by additive viewport width.

My complaint here was largely around the naming convention of `up(Md)` meaning "greater than the 'md' width definition", while `down(Md)` translates non-symmetrically to "less than next higher definition after 'md'" -- I get the logic behind this model, seeing breakpoints as ranges, but I would prefer a more precise interpretation.

**Comment by mg901** [comment]
@iRyanBell, I understand you, but I didn’t come up with the names for these functions myself. The styled-breakpoints API completely copies the [media query api](https://getbootstrap.com/docs/4.1/layout/overview/) from bootstrap (145k stars). So we can say with complete confidence that this is the standard for the industry. Yes, English is not my first language, but bootstrap was invented in San Francisco. For some reason, I have no doubts about the correctness of the name)) Thanks again for your interest.))
