### ISSUE TITLE
useBreakpoint doesn't work if you don't use a styled components theme

### ISSUE THREAD

**Issue by fragosti** [mg901/styled-breakpoints#904]
Seems like this should be easy to get around

https://codesandbox.io/s/styled-components-hooks-api-forked-spo18?file=/src/app.tsx

**Comment by mg901** [comment]
@fragosti Thank you! I'l fix it soon.

**Comment by mg901** [comment]
@fragosti done! See [example](https://codesandbox.io/s/styled-components-hooks-api-6q6w8?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fapp.tsx&theme=dark).
