### ISSUE TITLE
Queries in emotion css blocks have broken types

### ISSUE THREAD

**Issue by filipnathanel** [mg901/styled-breakpoints#971]
Hi Maxim!

First of all: many thanks for such a great library :)

I am writing as I have stumbled upon a potential bug that relates to Typescript.

the following line of code will result in a Type Error
```ts
import { css } from "@emotion/react";
import { down } from "styled-breakpoints";

const myReusableCss = css`
  ${down("xs")}{
    background: red;
  }
`
```

you can check the reproduction in a Code Sandbox:

https://codesandbox.io/s/stupefied-hertz-0z2b6?file=/src/MyComponent.ts

I might take a deeper look into code later on in the week to see whether I could come up with a solution.

**Comment by filipnathanel** [comment]
Or maybe I just don't understand emotion's API :man_shrugging: ...

I made it work by explicitly passing props from the outer scope.

```ts
import { css } from "@emotion/react";
import { down } from "styled-breakpoints";

const myReusableCss = (props) => css`
  ${down("xs")(props)}{
    background: red;
  }
`
```

**Comment by mg901** [comment]
@filipnathanel, hello. Thank you so much for discovering this issue. Yes, this is indeed a type bug. Since the css type from styled-components is not compatible with the type from @ emotion / styled. I'll be working on fixing this issue shortly.)

**Comment by mg901** [comment]
@filipnathanel Why are you using css function instead of styled?

**Comment by filipnathanel** [comment]
@mg901 

I don't know how `styled` would satisfy my need. The need being styles composition (sometimes dynamic) and from what I have gathered `css` is the way to go...

As per emotion docs:
https://emotion.sh/docs/styled#composing-dynamic-styles

**Comment by mg901** [comment]
@filipnathanel, now everything all right.))

**Comment by mg901** [comment]
@filipnathanel did I manage to solve your problem?

**Comment by filipnathanel** [comment]
@mg901 Thanks for keeping me in the loop.

The type error is missing however the breakpoint still doesn't work without props being explicitly passed to the breakpoint.

I have update the code sandbox with new version and an example 
https://codesandbox.io/s/stupefied-hertz-0z2b6?file=/src/MyComponent.ts

I think it has something with this issue https://github.com/emotion-js/emotion/issues/1085

**Comment by mg901** [comment]
@filipnathanel In the near future I will investigate this issue and try to solve your problem.

**Comment by mg901** [comment]
@@filipnathanel, sorry for long answering you for a long time. I have researched the given question. The css function in @ react / emotion doesn't know anything from the theme, unlike styled-components. For this reason, you need to make [atomic mixins](https://codesandbox.io/s/withered-cdn-xbkj0?file=/src/MyComponent.ts) that know nothing about breakpoints. In [this issue](https://github.com/emotion-js/emotion/issues/217) describes a similar problem. If you have any problems in solving your problems, turn around. I am always happy to help you.)

**Comment by mg901** [comment]
@filipnathanel, bro I was able to help you in solving the problem?
